import { User } from './User'

export const USERS:User[] = [
  {
    "id": 1,
    "username": "Bret",
    "name": "Leanne",
    "surname":  "Graham",
    "password": "Ufe6c6cdf28",
    "gender": "male",
    "email": "Sincere@april.biz",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Kulas Light",
    "suite": "Apt. 556",
  },
  {
    "id": 2,
    "username": "Antonette",
    "name": "Ervin",
    "surname":  "Howell",
    "password": "Ufe6c6cdf28",
    "gender": "male",
    "email": "Shanna@melissa.tv",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Victor Plains",
    "suite": "Suite 879",
  },
  {
    "id": 3,
    "username": "Samantha",
    "name": "Clementine",
    "surname": " Bauch",
    "password": "Ufe6c6cdf28",
    "gender": "female",
    "email": "Nathan@yesenia.net",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Douglas Extension",
    "suite": "Suite 847",
  },
  {
    "id": 4,
    "username": "Karianne",
    "name": "Patricia",
    "surname": " Lebsack",
    "password": "Ufe6c6cdf28",
    "gender": "female",
    "email": "Julianne.OConner@kory.org",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Hoeger Mall",
    "suite": "Suite 55",
  },
  {
    "id": 5,
    "username": "Kamren",
    "name": "Chelsey",
    "surname": "Dietrich",
    "password": "Ufe6c6cdf28",
    "gender": "female",
    "email": "Lucio_Hettinger@annie.ca",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Skiles Walks",
    "suite": "Suite 351",
  },
  {
    "id": 6,
    "username": "Leopoldo_Corkery",
    "name": "Dennis",
    "surname": "Schulist",
    "password": "Ufe6c6cdf28",
    "gender": "male",
    "email": "Karley_Dach@jasper.info",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Norberto Crossing",
    "suite": "Apt. 950",
  },
  {
    "id": 7,
    "username": "Elwyn.Skiles",
    "name": "Kurtis",
    "surname": "Weissnat",
    "password": "Ufe6c6cdf28",
    "gender": "male",
    "email": "Telly.Hoeger@billy.biz",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Rex Trail",
    "suite": "Suite 280",
  },
  {
    "id": 8,
    "username": "Maxime_Nienow",
    "name": "Nicholas",
    "surname": "Runolfsdottir",
    "password": "Ufe6c6cdf28",
    "gender": "female",
    "email": "Sherwood@rosamond.me",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Ellsworth Summit",
    "suite": "Suite 729",
  },
  {
    "id": 9,
    "username": "Delphine",
    "name": "Glenna",
    "surname": "Reichert",
    "password": "Ufe6c6cdf28",
    "gender": "female",
    "email": "Chaim_McDermott@dana.io",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Dayna Park",
    "suite": "Suite 449",
  },
  {
    "id": 10,
    "username": "Moriah.Stanton",
    "name": "Clementina",
    "surname": "DuBuque",
    "password": "Ufe6c6cdf28",
    "gender": "female",
    "email": "Rey.Padberg@karina.biz",
    "phone": 177073689,
    "zipcode": 15412,
    "voivodship": "West Pomerania",
    "street": "Kattie Turnpike",
    "suite": "Suite 198",
  }
];
